version: '3.4'

services:
  schoolmomentapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionString=Data Source=sqlserverService;Database=SchoolDb/;User Id=sa;Password=BigPassw0rd
    ports:
      - "49630:80"
      - "49631:443"
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
 